apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: test-live-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-live-go 
  name: test-live-go
  namespace: test-live-go
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-live-go
    weight: 100 
